name: monograph_management_system
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.2
  share_plus: ^10.1.2
  shared_preferences_web: ^2.1.0
  google_fonts: ^4.0.0
  cloud_firestore: ^5.5.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

